/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Feature {
  created_at: string;
  id: string;
  location: string | null;
  removed_at: string | null;
  updated_at: string;
}

export interface Geometry {
  created_at: string;
  feature_id: string;
  geometry: string;
  hash: string;
  removed_at: string | null;
}

export interface DB {
  feature: Feature;
  geometry: Geometry;
}
